package org.jammingdetection.ingestion.model;
import org.jammingdetection.generated.ingestion.tables.records.AdsbFileRecord;

/**
 * Represents a single ingested ADS-B raw message file: one hour of data
 * from one sensor, on one date. It is important to keep the same data structure
 * as the explained.
 *
 * <p>Wraps the {@link AdsbFileRecord} generated by jOOQ, exposing
 * only the identifier needed elsewhere in the ingestion pipeline.
 */
public class AdsbFile {
    private long id;
    private short hour;
    private long sensorSerial;
    private int totalMsgCount;
    private long timeToDecode;

    public AdsbFile (AdsbFileRecord record){
        this.id = record.getId();
        this.hour = record.getHour();
        this.sensorSerial = record.getSensorSerial();
        this.totalMsgCount = record.getTotalMsgCount();
        this.timeToDecode = record.getTimeToDecode();
    }

    public long getId() {
        return id;
    }
}
